// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRbehkZdAKQNzsKzmH3Rcs5kH6qZtrs9k',
    appId: '1:769768861452:web:10ca83cfa12005293aa329',
    messagingSenderId: '769768861452',
    projectId: 'fit-u-2005',
    authDomain: 'fit-u-2005.firebaseapp.com',
    storageBucket: 'fit-u-2005.firebasestorage.app',
    measurementId: 'G-B2D2VQQ1RF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbkzqPt3BRnA0GniqYvTTaj-_ufqBDXns',
    appId: '1:769768861452:android:d226327c83989f633aa329',
    messagingSenderId: '769768861452',
    projectId: 'fit-u-2005',
    storageBucket: 'fit-u-2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlGxRE99VmOqhoysp1fTbWs0V7dLtBwE',
    appId: '1:769768861452:ios:2bfa2e2ec32b26bf3aa329',
    messagingSenderId: '769768861452',
    projectId: 'fit-u-2005',
    storageBucket: 'fit-u-2005.firebasestorage.app',
    iosClientId: '769768861452-grjlmsgsjs6uqqvhc7vq4u57sbvonh07.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMlGxRE99VmOqhoysp1fTbWs0V7dLtBwE',
    appId: '1:769768861452:ios:2bfa2e2ec32b26bf3aa329',
    messagingSenderId: '769768861452',
    projectId: 'fit-u-2005',
    storageBucket: 'fit-u-2005.firebasestorage.app',
    iosClientId: '769768861452-grjlmsgsjs6uqqvhc7vq4u57sbvonh07.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRbehkZdAKQNzsKzmH3Rcs5kH6qZtrs9k',
    appId: '1:769768861452:web:f2b66241b81f088b3aa329',
    messagingSenderId: '769768861452',
    projectId: 'fit-u-2005',
    authDomain: 'fit-u-2005.firebaseapp.com',
    storageBucket: 'fit-u-2005.firebasestorage.app',
    measurementId: 'G-HHYF4JLNDF',
  );

}